# Generated by Django 4.2.16 on 2024-09-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasement',
            name='id',
        ),
        migrations.AddField(
            model_name='releasement',
            name='I_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='releasement',
            name='R_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
