# Generated by Django 4.2.16 on 2024-09-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='N_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
