# Generated by Django 4.2.16 on 2024-09-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_releasement_id_releasement_i_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='account',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
