# Generated by Django 4.2.16 on 2024-09-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_account_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='N_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='S_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
