# Generated by Django 4.2.16 on 2024-09-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_note_n_id_alter_note_s_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='fllow_num',
            new_name='follow_num',
        ),
        migrations.AlterField(
            model_name='note',
            name='N_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
