# Generated by Django 4.2.16 on 2024-09-22 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_fllow_num_note_follow_num_alter_note_n_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteISopen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_public', models.BooleanField(blank=True, default=False, null=True)),
                ('S_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
