# Generated by Django 4.2.16 on 2024-09-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='Syllabus',
            field=models.FileField(blank=True, null=True, upload_to='Course/syllabus/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='calendar',
            field=models.FileField(blank=True, null=True, upload_to='Course/calendar/'),
        ),
    ]
