# Generated by Django 4.2.16 on 2024-10-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_models', '0004_alter_course_syllabus_alter_course_calendar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='R_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
