# Generated by Django 4.2.16 on 2024-10-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_models', '0005_alter_resource_r_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dowork',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='work/students'),
        ),
        migrations.AlterField(
            model_name='work',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='work/teacher'),
        ),
    ]
