# Generated by Django 4.2.16 on 2024-12-12 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_models', '0011_remove_admin_passward_remove_student_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discuss',
            old_name='student',
            new_name='S_id',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='name',
        ),
        migrations.AddField(
            model_name='discuss',
            name='T_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='global_models.teacher'),
        ),
        migrations.AddField(
            model_name='discuss',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='S_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='global_models.student'),
        ),
        migrations.AddField(
            model_name='reply',
            name='T_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='global_models.teacher'),
        ),
        migrations.AddField(
            model_name='reply',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discuss',
            name='D_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reply',
            name='R_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
