# Generated by Django 4.2.16 on 2024-12-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_models', '0012_rename_student_discuss_s_id_remove_reply_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discuss',
            old_name='S_id',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='discuss',
            name='T_id',
        ),
        migrations.RemoveField(
            model_name='discuss',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='S_id',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='T_id',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='likes',
        ),
        migrations.AddField(
            model_name='reply',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discuss',
            name='D_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reply',
            name='R_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
