# Generated by Django 4.2.16 on 2024-12-19 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_models', '0014_rename_student_discuss_s_id_remove_reply_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('K_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='phoneNumber',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phoneNumber',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='KeyWordDiscuss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='global_models.discuss')),
                ('K_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='global_models.keyword')),
            ],
        ),
    ]
