# Generated by Django 4.2.16 on 2024-12-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_models', '0015_keyword_student_email_student_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
