# Generated by Django 4.2.16 on 2024-12-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_models', '0016_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phoneNumber',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
